apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: talos-api
  namespace: talos-system
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: talos.local
    http:
      paths:
      - path: /api(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
            service:
              name: talos-gateway
              port:
                number: 8000
      - path: /audit(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: talos-audit-service
            port:
              number: 8000
      - path: /mcp(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: talos-mcp-connector
            port:
              number: 8082
