apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: talos-system

resources:
- namespace.yaml
- gateway/serviceaccount.yaml
- gateway/deployment.yaml
- gateway/service.yaml
- gateway/migration-job.yaml
- dashboard/deployment-service.yaml
- audit/deployment-service.yaml
- mcp-connector/deployment-service.yaml
- ucp-connector/deployment-service.yaml
- ingress/deployment-service.yaml
- ingress/configmap.yaml
- aiops/deployment-service.yaml
- ingress-dashboard.yaml
- ingress-api.yaml
- network-policies.yaml
- infra/postgres.yaml
- infra/redis.yaml
- infra/ollama.yaml
- chat-agent/deployment-service.yaml

images:
- name: talos-gateway
  newName: ghcr.io/talosprotocol/talos-gateway
  newTag: "v-0.0.0"
- name: talos-audit-service
  newName: ghcr.io/talosprotocol/talos-audit-service
  newTag: "v-0.0.0"
- name: talos-mcp-connector
  newName: ghcr.io/talosprotocol/talos-mcp-connector
  newTag: "v-0.0.0"
- name: talos-dashboard
  newName: ghcr.io/talosprotocol/talos-dashboard
  newTag: "v-0.0.0"
- name: talos-ucp-connector
  newName: ghcr.io/talosprotocol/talos-ucp-connector
  newTag: "v-0.0.0"
- name: talos-aiops
  newName: ghcr.io/talosprotocol/talos-aiops
  newTag: "v-0.0.0"
- name: talos-ingress
  newName: ghcr.io/talosprotocol/talos-ingress
  newTag: "v-0.0.0"
