apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "talos.fullname" . }}
  labels:
    {{- include "talos.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "talos.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      labels:
        {{- include "talos.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "talos.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: p2p
              containerPort: {{ .Values.service.p2pPort }}
              protocol: TCP
            - name: dht
              containerPort: {{ .Values.service.dhtPort }}
              protocol: UDP
          env:
            - name: TALOS_DIFFICULTY
              value: "{{ .Values.talos.difficulty }}"
            - name: TALOS_LOG_LEVEL
              value: "{{ .Values.talos.logLevel }}"
            - name: TALOS_DATA_DIR
              value: "{{ .Values.talos.dataDir }}"
            - name: TALOS_KEYS_DIR
              value: "{{ .Values.talos.keysDir }}"
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.talos.dataDir }}
            - name: keys
              mountPath: {{ .Values.talos.keysDir }}
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "talos.fullname" . }}-data
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: keys
          secret:
            secretName: {{ include "talos.fullname" . }}-keys
            optional: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
