[tool.mypy]
python_version = "3.11"
strict = true
ignore_missing_imports = false
mypy_path = "src"
explicit_package_bases = true
warn_unused_ignores = false
plugins = ["pydantic.mypy"]

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
warn_untyped_fields = true

[[tool.mypy.overrides]]
module = [
  "jsonschema",
  "jsonschema.*",
  "yaml",
  "yaml.*",
  "msgpack",
  "msgpack.*",
  "starlette",
  "starlette.*",
  "fastapi",
  "fastapi.*",
  "prometheus_client",
  "prometheus_client.*",
]
ignore_missing_imports = true
disable_error_code = ["import-untyped"]
